[package]
name = "quickentity-rs"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.22", features = ["derive"] }
itertools = "0.10.3"
json-patch = "0.2.6"
linked-hash-map = { version = "0.5.6", features = ["serde_impl"] }
md5 = "0.7.0"
rayon = "1.5.3"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = { version = "1.0.81", features = [
    "arbitrary_precision",
    "preserve_order",
] }
serde_with = "2.0.1"
ts-rs = "6.2.0"
time-graph = { version = "0.1.3", features = ["table"] }
egui = "0.19.0"
egui_extras = { version = "0.19.0", features = ["image"] }
image = { version = "0.24", features = ["png"] }
eframe = "0.19.0"
rfd = "0.10.0"

[dev-dependencies]
criterion = "0.4.0"

[[bench]]
name = "conversion"
harness = false

[[bin]]
name = "quickentity-rs"
path = "src/main.rs"

[[bin]]
name = "quickentity-gui"
path = "src/gui.rs"
